spring.application.name=consumidor-archivos
server.port=8085
spring.rabbitmq.host=172.31.19.190
spring.rabbitmq.port=5672
app.rabbitmq.queue.horarios=cola-horarios
app.files.path=C:/temp/transport-logs/