spring.application.name=consumidor-archivos
server.port=8085
spring.rabbitmq.host=172.31.19.190
spring.rabbitmq.port=5672
app.rabbitmq.queue.horarios=cola-horarios
app.files.path=/app/archivos_generados/

# sudo docker run -d -p 8085:8085 --name consumidor-archivos gonzaduoc/consumidor-archivos:latest